softeerbootcamp/Team3

.vscode/settings.json, frontend/gathergo/.eslintrc.json, frontend/gathergo/.gitignore, frontend/gathergo/.prettierrc.json, frontend/gathergo/package-lock.json, frontend/gathergo/package.json, frontend/gathergo/src/main.ts
https://github.com/softeerbootcamp/Team3/issues/10
=> feat: eslint and prettier setting

backend/gathergo/src/main/java/lightning/gathergo/exception/ErrorCode.java, backend/gathergo/src/main/java/lightning/gathergo/service/RegionService.java
구현한 CustomGlobalException 활용하여 예외 처리
https://github.com/softeerbootcamp/Team3/issues/24
=> [Resolves #24] Region 예외처리 구현

backend/gathergo/src/main/java/lightning/gathergo/controller/CategoryController.java, backend/gathergo/src/main/java/lightning/gathergo/dto/CategoryDto.java, backend/gathergo/src/main/java/lightning/gathergo/mapper/CategoryDtoMapper.java, backend/gathergo/src/main/java/lightning/gathergo/model/Category.java, backend/gathergo/src/main/java/lightning/gathergo/repository/CategoryRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/CategoryService.java
- 상세 내용 1
- 상세 내용 2
</details>
<details> 
<summary>구현 사항 2</summary> </summary>
- 상세 내용 1
- 상세 내용 2
</details>
- 내용을 작성해주세요
=> [Resolves #4] 카테고리 api 구현

frontend/gathergo/src/Profile/profile.css, frontend/gathergo/src/Profile/profile.html, frontend/gathergo/src/login/login.css, frontend/gathergo/src/login/login.html, frontend/gathergo/src/login/login.ts
- 로그인 다시 페이지 만듦
- 프로필 사진 첨부시 바뀜
</details>
- 프로필 전부 rem, 혹은 %로 바꾸기
- 프로필 폰트, 크기 변경
- 프로필 textarea 설정 변경
=> Redesign/12/login UI

frontend/gathergo/initialstate.ts
- initialstate.js 작성
</details>
=> #56 initialstate.ts 작성

frontend/gathergo/index.html, frontend/gathergo/src/components/modals/errorModal.ts, frontend/gathergo/src/css/errormodal.css
- 에러! 디자인
- 모달 버튼, 백그라운드 이벤트 달기
</details>
=> Error modal

backend/gathergo/src/main/java/lightning/gathergo/dto/ImageDto.java, backend/gathergo/src/main/java/lightning/gathergo/service/ImageService.java
<details> <summary> svg에 대해서 자료형 처리 </summary>
- svg+xml로 들어오게 되는 것을 svg로만 처리하도록 함
</details>
- png로만 올리도록 할 지
- 프론트 입장에서는 png로만 해주는게 요청 url이 바뀌지 않아서 편함
=> [Resolves #95] S3 이미지 업로더 구현

frontend/gathergo/firebase-messaging-sw.js
https://github.com/softeerbootcamp/Team3/issues/101
<details> <summary> 서비스워커 추가 </summary>
- 서비스워커 추가
</details>
- 내용을 작성해주세요
=> feat: firebase-messaging-sw.js 추가

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/AuthController.java, backend/gathergo/src/main/java/lightning/gathergo/dto/GatheringDto.java, backend/gathergo/src/main/java/lightning/gathergo/repository/UserArticleRelationshipRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java, backend/gathergo/src/main/java/lightning/gathergo/service/UserService.java
[feat : id로 유저 얻어오는 기능]
[fix : 쿼리수정]
[fix : 참여 여부 및 호스트인지 확인하는 로직 수정]
[fix : 예외처리에서 response가 반환되도록 수정]
[refactor : dto가 현재원 정보도 전달하도록 변경]
[refactor : 현재원 정보 반환하도록 수정]
[refactor : 주석 날림]
- 내용을 작성해주세요
=> [Resolve#103] 현재인원 수도 같이 넘어가도록 리팩토링

backend/gathergo/src/main/java/lightning/gathergo/controller/AuthController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/UserController.java, backend/gathergo/src/main/java/lightning/gathergo/dto/LoginDto.java, backend/gathergo/src/main/java/lightning/gathergo/dto/SignupDto.java, backend/gathergo/src/main/java/lightning/gathergo/dto/UserDto.java, backend/gathergo/src/main/java/lightning/gathergo/model/Session.java, backend/gathergo/src/main/java/lightning/gathergo/service/UserService.java
<details> <summary>유저 프로필 조회 API 추가</summary>
- 참여중인 게시글 반환
- 호스팅 하는 게시글 반환
- 한 줄 소개 등 유저 정보 반환
</details>
=> [Resolves #97] 유저 프로필 조회 API 추가

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java
쿠키에 세션아이디가 없을 때도 상세페이지를 볼 수 있도록 수정
https://github.com/softeerbootcamp/Team3/issues/106
=> fix : 로그인하지 않았을 때 상세페이지 볼 수 있도록

backend/gathergo/src/main/java/lightning/gathergo/model/Comment.java
https://github.com/softeerbootcamp/Team3/issues/108
댓글 작성 시 9시간 전이라고 뜨던 문제 수정
- 내용을 작성해주세요
=> [Resolve #108] 댓글 timezone

backend/gathergo/src/main/java/lightning/gathergo/dto/UserDto.java
<details> <summary>UserDto.ProfileResponse 클래스의 비밀번호 필드 삭제</summary>
- 비밀번호 필드 삭제
- 참여중인 게시글, 호스팅 하는 게시글 리스트 List.copyOf() 방어적 복사 추가
</details>
- 내용을 작성해주세요
=> [Resolves #110] 사용자 프로필 조회 시 비밀번호 반환하지 않도록

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
https://github.com/softeerbootcamp/Team3/issues/112
게시물 수정 후 상세조회 버그 해결
- 내용을 작성해주세요
=> [Resolve #112] 게시물 수정 후 상세조회

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/dto/CommentDto.java, backend/gathergo/src/main/java/lightning/gathergo/service/CommentService.java
https://github.com/softeerbootcamp/Team3/issues/114
dto에 관련 프로퍼티 추가
현재 접속중인 userId와 댓글의 userId 비교해주는 메서드 작성
- 내용을 작성해주세요
=> [Resolve #114] 내가 쓴 댓글 확인 기능

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/dto/CommentDto.java, backend/gathergo/src/main/java/lightning/gathergo/service/CommentService.java
Reverts softeerbootcamp/Team3#120
=> Revert "[Resolve #114] 내가 쓴 댓글 확인 기능"

backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
- repository에 카테고리 정보만으로 게시물 리스트를 얻어오는 메서드 작성
- 위에서 구현한 메서드를 바탕으로 서비스에서 카테고리 정보만으로 게시물 리스트를 controller에 넘겨줌
=> [Resolve #119] 카테고리만으로 글 검색하기

backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java
https://github.com/softeerbootcamp/Team3/issues/115
<details> <summary>게시물 정렬</summary>
모이는 날이 가장 현재시간과 가까운 글이 위로 뜨도록
order by meetingDay (asc)
</details>
<details> 
<summary>댓글 정렬</summary> </summary>
예전 댓글이 위로 뜨도록
order by date (asc)
</details>
- 내용을 작성해주세요
=> [Resolve #115] 게시물 및 댓글 정렬

backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java
Reverts softeerbootcamp/Team3#124
이전 커밋 내용이 갑자기 없어졌습니다. 해결 후 다시 올리겠습니다.
=> Revert "[Resolve #115] 게시물 및 댓글 정렬"

backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
order by pr에서 이전 커밋이 누락되었던 문제 해결 후 다시 pr 올립니다.
=> merge 누락으로 인한 빌드 오류 수정 후 다시 pr

backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
https://github.com/softeerbootcamp/Team3/issues/115
검색 조건이 없을 때도 order by 되도록
- 내용을 작성해주세요
=> [Resolve #115]

backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java
article repository에서 find 관련 메서드 쿼리 수정
=> [Resolve #64] 닫힌 게시물들은 안보여지도록

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/repository/ArticleRepository.java, backend/gathergo/src/main/java/lightning/gathergo/scheduler/ArticleScheduler.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java, backend/gathergo/src/main/java/lightning/gathergo/service/SchedulerService.java
<details> <summary>스케줄러</summary>
- 1분마다 글 닫기 기능이 수행됨
- 검색 속도 향상을 위해 meetingDay에 clustered index 생성
</details>
<details> 
<summary>호스트도 글에 참가한 것으로 변경</summary> </summary>
</details>
=> [Resolve #131, #136] 게시물 닫기 스케줄러 및 호스트 참가

backend/gathergo/src/main/java/lightning/gathergo/controller/UserController.java, backend/gathergo/src/main/java/lightning/gathergo/dto/GatheringDto.java, backend/gathergo/src/main/java/lightning/gathergo/dto/UserDto.java, backend/gathergo/src/main/java/lightning/gathergo/repository/UserRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/UserService.java, backend/gathergo/src/main/resources/application-dev.yml
<details> <summary>프로필 페이지에서 현재 참여인원 조회하도록 필드 추가</summary>
- 반환 DTO Article -> ArticlePartialDto로 변경
- 현재 참여인원 CountService 참조해 반환
</details>
=> [Resolves #133] 프로필 수정 API

backend/gathergo/Dockerfile, backend/gathergo/docker-compose.yml, backend/gathergo/src/main/resources/application-dev.yml
Reverts softeerbootcamp/Team3#140
=> Revert "fix : merge conflict 해결"

frontend/gathergo/public/assets/Icons/chevronupIcon.svg, frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/components/card/CardModal.ts, frontend/gathergo/src/components/fba/fba.ts, frontend/gathergo/src/components/modals/notiModal.ts, frontend/gathergo/src/components/profile/profileMain.ts, frontend/gathergo/src/css/feedRead.css, frontend/gathergo/src/css/index.css, frontend/gathergo/src/css/profile.css, frontend/gathergo/src/pages/home.ts, frontend/gathergo/src/pages/post.ts, frontend/gathergo/src/store/reducers.ts
<details> <summary>만남 참가 api</summary>
- 만남 참가
- 만남 취소
- 만남 삭제(isclosed)
</details>
<details> 
<summary>fba</summary> </summary>
- 홈, 포스트 페이지에서 버튼을 누르면 최상단으로 자동 스크롤
</details>
- 내용을 작성해주세요
=> feat: 참가 api + fba

backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
- 이미 참가한 모임에 계속 참가할 수 있었던 이유 해결
=> [Resolve #144] 참가 버그 해결

frontend/gathergo/index.html, frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/components/card/Card.ts, frontend/gathergo/src/components/comment/CommentList.ts, frontend/gathergo/src/components/header/headerHome.ts, frontend/gathergo/src/components/header/headerHomeNav.ts, frontend/gathergo/src/components/modals/notiModal.ts, frontend/gathergo/src/components/sidebar/alarmSidebar.ts, frontend/gathergo/src/components/sidebar/log.ts, frontend/gathergo/src/css/index.css, frontend/gathergo/src/css/sidebar.css, frontend/gathergo/src/pages/home.ts, frontend/gathergo/src/store/actions.ts, frontend/gathergo/src/store/reducers.ts
<details> <summary>사이드바</summary>
- 버튼 클릭시 애니메이션
- log list 디자인
</details>
<details> 
<summary>참가 상호작용</summary> </summary>
- join cancel 기능 구현
- 이미 가득 찬 모임일경우 에러처리
</details>
- 내용을 작성해주세요
=> feat: sidebar, joincancel, join error처리

backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
=> [Resolve #156] 참여인원 버그 수정

frontend/gathergo/src/common/commonFunctions.ts, frontend/gathergo/src/components/card/CardModal.ts, frontend/gathergo/src/components/form/PostingForm.ts
<details> <summary>댓글 시간 오류 해결</summary>
- utils에 함수추가
- 게시물, 댓글 시간등록 로직 변경
</details>
- 내용을 작성해주세요
=> bug: 댓글 시간 오류 해결

frontend/gathergo/src/components/profile/tabEditMain.ts, frontend/gathergo/src/components/profile/tabLogoutModal.ts, frontend/gathergo/src/components/profile/tabProfile/profileUserInfo.ts, frontend/gathergo/src/css/profile.css
- 마감됨 제대로 출력됨
- 로그아웃
- 프로필 페이지 변경시 렌더링 제대로
</details>
=> #164 로그아웃 버그 수정

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/exception/ErrorCode.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java
=> [Resolve #151] 게시물 관련 예외처리

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/AuthController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/NotificationController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/SubscriptionController.java, backend/gathergo/src/main/java/lightning/gathergo/model/Notification.java, backend/gathergo/src/main/java/lightning/gathergo/model/Session.java, backend/gathergo/src/main/java/lightning/gathergo/repository/NotificationRepository.java, backend/gathergo/src/main/java/lightning/gathergo/repository/SubscriptionRepository.java, backend/gathergo/src/main/java/lightning/gathergo/repository/UserArticleRelationshipRepository.java, backend/gathergo/src/main/java/lightning/gathergo/service/FcmMessagingService.java, backend/gathergo/src/main/java/lightning/gathergo/service/SessionService.java, backend/gathergo/src/test/java/lightning/gathergo/controller/AuthControllerTest.java, backend/gathergo/src/test/java/lightning/gathergo/repository/SessionRepositoryTest.java, backend/gathergo/src/test/java/lightning/gathergo/service/CookieServiceTest.java, backend/gathergo/src/test/java/lightning/gathergo/service/SchedulerServiceTest.java, backend/gathergo/src/test/java/lightning/gathergo/service/SessionServiceTest.java
<details> <summary>글 수정, 댓글 등록 등 이벤트에 따른 push알림 추가</summary>
- 참여중인 게시글에 변경사항, 댓글 등록, 조기 종료 등이 발생하면 알림 발송
</details>
<details> 
<summary>참여하는 모임들에서 발생한 알림 반환</summary>
- 참여중인 게시글에서 발생한 알림들을 리스트로 반환하는 api 추가
</details>
- 실제 로그인 해서 테스트 해보기
=> [Resolves #167] 글 수정, 댓글 등록 등 이벤트에 따른 push알림, 참여 모임의 알림 리스트 반환

frontend/gathergo/README.md, frontend/gathergo/index.html, frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/common/constants.ts, frontend/gathergo/src/components/card/CardModal.ts, frontend/gathergo/src/components/profile/tabLogoutModal.ts
=> README 업데이트, alarm 부분 html에 추가

frontend/gathergo/.gitignore, frontend/gathergo/src/components/fba/chatBotOpenAI.js
<details> <summary>api 키 숨기기</summary>
- openaAi api 키 숨기기
</details>
=> bug: api 키 숨기기

frontend/gathergo/index.html, frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/components/card/CardList.ts, frontend/gathergo/src/components/fba/chatBotOpenAI.js, frontend/gathergo/src/store/reducers.ts
<details> <summary>lazy loading</summary>
- 카드 썸네일 생성시 40개씩 생성
- 마지막 카드를 observing
- 마지막 카드가 뷰포트에 등장하면 40개 추가 생성
</details>
- 내용을 작성해주세요
=> feat: lazyloading

backend/gathergo/src/test/java/lightning/gathergo/service/CountServiceTest.java
https://github.com/softeerbootcamp/Team3/issues/132
<details> <summary> Redis 현재 인원 수 테스트 </summary>
- 쓰레드를 여러 개 만들어 요청하도록 함
</details>
- 없음
=> test : redis  여러 쓰레드 간 동기성 확인

frontend/gathergo/src/components/form/PostingForm.ts
<details> <summary>잘못된 예외처리 수정</summary>
- 시간에 상관없이 모든 상황에서 예외처리 되던부분 수정.
</details>
- 내용을 작성해주세요
=> bug: posting 시간 예외처리 에러수정

frontend/gathergo/README.md, frontend/gathergo/firebase-messaging-sw.js, frontend/gathergo/index.html, frontend/gathergo/package-lock.json, frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/components/fba/chatBotOpenAI.js, frontend/gathergo/src/components/modals/notiModal.ts, frontend/gathergo/src/css/profile.css
- 댓글 참여하고 누가 댓글 작성하면 크롬 메시지가 뜹니다.
</details>
=> Alarm onmessage

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/DummyController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/SubscriptionController.java, backend/gathergo/src/main/java/lightning/gathergo/service/FcmMessagingService.java, backend/gathergo/src/test/java/lightning/gathergo/repository/NotificationRepositoryTest.java, backend/gathergo/src/test/java/lightning/gathergo/service/FcmMessagingServiceTest.java
<details> <summary> #188 빌드 에러 수정</summary>
- 빌드 안되던 문제 해결
메서드 시그니처 변경
</details>
=> [Resolves #188] 빌드 에러 수정

backend/gathergo/src/main/java/lightning/gathergo/config/RedisConfig.java, backend/gathergo/src/main/java/lightning/gathergo/service/ArticleService.java, backend/gathergo/src/main/java/lightning/gathergo/service/CountService.java
=> [Resolve #190] 레디스 날림

frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/components/card/CardList.ts, frontend/gathergo/src/components/card/CardModal.ts, frontend/gathergo/src/components/header/headerDefaultNav.ts
<details> <summary>헤더 수정</summary>
- 프로필의 링크 수정
</details>
<details> 
<summary>동시성 처리</summary> </summary>
- curr이 total 보다 커지지 않도록
</details>
- 내용을 작성해주세요
=> bug: 헤더 수정, 동시성 처리

backend/gathergo/src/main/java/lightning/gathergo/controller/ArticleController.java, backend/gathergo/src/main/java/lightning/gathergo/controller/NotificationController.java
<details> <summary>notification dto에 게시글의 meetingDay 매핑 로직 수정</summary>
</details>
=> [Resolves #197] 유저가 수신한 알림 리스트 중 일부 만남의 만남 일자 누락오류

frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/components/form/PostingForm.ts, frontend/gathergo/src/components/modals/notiModal.ts, frontend/gathergo/src/css/sidebar.css, frontend/gathergo/src/store/reducers.ts
<details> <summary>포스팅 만들기 error</summary>
- 포스팅 만들기 후 modal 생성
- 생성 후 리다이렉트
</details>
<details> 
<summary>포스팅 수정 error</summary> </summary>
- 포스팅 수정 후 modal 생성
- 수정 후 리다이렉트
</details>
- 내용을 작성해주세요
=> bug: 포스팅 수정시 리다이렉트 안되는 에러수정

frontend/gathergo/src/common/Fetches.ts, frontend/gathergo/src/common/constants.ts, frontend/gathergo/src/components/sidebar/alarmSidebar.ts, frontend/gathergo/src/components/sidebar/log.ts, frontend/gathergo/src/css/profile.css, frontend/gathergo/src/pages/home.ts, frontend/gathergo/src/server/initialstate.ts, frontend/gathergo/src/store/actions.ts, frontend/gathergo/src/store/reducers.ts
=> 알람 사이드바 구현

backend/gathergo/src/main/java/lightning/gathergo/controller/NotificationController.java, backend/gathergo/src/main/java/lightning/gathergo/model/Notification.java, backend/gathergo/src/main/java/lightning/gathergo/service/FcmMessagingService.java
<details> <summary>유저가 수신한 알림 리스트 내림차순으로 정렬</summary>
</details>
=> [Resolves 199] 유저가 수신한 알림 리스트 오름차순 정렬되는 문제
